"""add user_id to recipes

Revision ID: 5be7bd6acdac
Revises: 71feb1a58a54
Create Date: 2026-09-14 23:50:26.392195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be7bd6acdac'
down_revision: Union[str, Sequence[str], None] = '71feb1a58a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    # Opción A: no conservamos las recetas de prueba existentes.
    # Necesario para poder agregar user_id como NOT NULL.
    op.execute("DELETE FROM recipes")
    op.add_column('recipes', sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(
        'fk_recipes_user_id_users',
        'recipes',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recipes_user_id_users', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
