"""add puntaje to recipes and user_puntajes table

Revision ID: 8655bbfe4c55
Revises: 80eda8b9e3b9
Create Date: 2026-09-15 21:30:38.796538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8655bbfe4c55'
down_revision: Union[str, Sequence[str], None] = '80eda8b9e3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_puntajes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recipe_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_puntajes_user_recipe')
    )
    op.add_column('recipes', sa.Column('puntaje', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'puntaje')
    op.drop_table('user_puntajes')
    # ### end Alembic commands ###
